burgercriz/urls.py
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.urls import path, include

from .views import HomeView, UserUpdateView, help_view, apps_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/profile/', login_required(UserUpdateView.as_view()), name='profile'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', HomeView.as_view(), name='home'),
    path('apps/', apps_view, name='apps'),
    path('help/', help_view, name='help'),
    path('cards/', include('cards.urls')),
]

cards/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required

from .views import CardListView, CardUpdateView, CardCreateView, CardDeleteView, add_to_deck, DeckCreateView

app_name = 'cards'
urlpatterns = [
    path('', CardListView.as_view(), name='list'),
    path('new/', login_required(CardCreateView.as_view()), name='create'),
    path('<int:pk>/', login_required(CardUpdateView.as_view()), name='update'),
    path('<int:card_id>/to/new/', login_required(DeckCreateView.as_view()), name='new_deck'),
    path('<int:card_id>/to/<int:deck_id>', login_required(add_to_deck), name='add_to_deck'),
    path('<int:pk>/delete/', login_required(CardDeleteView.as_view()), name='delete'),
]

cards/models.py
from django.db import models
from django.contrib.auth.models import User

from markdownfield.models import MarkdownField, RenderedMarkdownField
from markdownfield.validators import VALIDATOR_NULL


class Tag(models.Model):
    tag = models.SlugField(blank=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    created_date = models.DateTimeField('Date de création', auto_now_add=True)

    def __str__(self):
        return self.tag


class Card(models.Model):
    text = MarkdownField('Texte de la carte', rendered_field='text_rendered', validator=VALIDATOR_NULL, default="Tapez le texte de votre carte (en utilisant **Markdown**)")
    text_rendered = RenderedMarkdownField('Texte de la carte en HTML')
    TYPE_CHOICES = (
        (0, "Toss"),
        (1, "Nuggets"),
        (2, "Sel ou poivre"),
        (3, "Menu (cordon bleu)"),
        (4, "Menu (cordon rouge)"),
        (5, "L'addition"),
        (6, "Burger de la mort"),

    )

    type = models.PositiveSmallIntegerField(
        'Type de carte', choices=TYPE_CHOICES, default=1)
    public = models.BooleanField('Carte publique ?', default=True)

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    tags = models.ManyToManyField(Tag, blank=True)

    modified_date = models.DateTimeField('Date de modification', auto_now=True)
    created_date = models.DateTimeField('Date de création', auto_now_add=True)

    def __str__(self):
        return "Carte " + str(self.TYPE_CHOICES[self.type][1]).lower() + ' n°' + str(self.id)

    class Meta:
        verbose_name = "Carte"
        verbose_name_plural = "Cartes"


class Deck(models.Model):
    name = models.CharField('Paquet de cartes', max_length=128)
    cards = models.ManyToManyField(Card, blank=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    public = models.BooleanField('Paquet public ?', default=True)

    created_date = models.DateTimeField('Date de création', auto_now_add=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Paquet de cartes"
        verbose_name_plural = "Paquets de cartes"

burgercriz/views.py
from django.views import generic
from django.shortcuts import get_object_or_404, render
from django.contrib.auth.models import User

from cards.models import Card

class HomeView(generic.ListView):
    template_name = 'home.html'
    model = Card

    ordering = ['-id']

class UserUpdateView(generic.UpdateView):
    model = User
    fields = ('first_name', 'last_name', 'email',)

    success_url = '/'

    def get_object(self):
        return get_object_or_404(User, pk=self.request.user.pk)

def help_view(request):
    return render(request, 'help.html')

def apps_view(request):
    return render(request, 'apps.html')
    

cards/views.py
from django.views.generic import ListView, UpdateView, CreateView, DeleteView
from django.shortcuts import get_object_or_404
from django.http import HttpResponseRedirect, HttpResponseForbidden
from django.urls import reverse

from .models import Card, Tag, Deck

class CardCreateView(CreateView):
    model = Card
    fields = ['text', 'type', 'public', 'tags']

    success_url = '/cards/'

    def form_valid(self, form):
        form.instance.user = self.request.user
        
        return super().form_valid(form)

class CardListView(ListView):
    model = Card
    paginate_by = 21

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tags'] = Tag.objects.all()
        context['public_decks'] = Deck.objects.filter(public=True)
        context['card_types'] = Card.TYPE_CHOICES
        if self.request.user.is_authenticated:
            context['decks'] = Deck.objects.filter(public=True, user = self.request.user)
        return context

    def get_queryset(self):
        tag = self.request.GET.get('tag')
        deck = self.request.GET.get('deck')
        type = self.request.GET.get('type')
        if tag:
            self.tag = get_object_or_404(Tag, tag__startswith=tag)
            return Card.objects.filter(tags=self.tag).order_by('-modified_date')
        if deck:
            self.deck = get_object_or_404(Deck, name__startswith=deck)
            return self.deck.cards.filter(public=True).order_by('-modified_date')
        if type:
            return Card.objects.filter(type=type).order_by('-modified_date')
        else:
            return Card.objects.filter(public=True).order_by('-modified_date')

class CardUpdateView(UpdateView):
    model = Card
    fields = ['text', 'type', 'public', 'tags']
    success_url = '/cards/'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['decks'] = Deck.objects.filter(user=self.request.user)
        return context

    def dispatch(self, request, *args, **kwargs):
        card = get_object_or_404(Card, pk=self.kwargs['pk'])
        if request.user != card.user:
            return HttpResponseForbidden("Dis donc, c'est interdit ça d'éditer la carte des petits copains !")
        return super().dispatch(request, *args, **kwargs)

class CardDeleteView(DeleteView):
    model = Card
    success_url = '/cards/'

    def dispatch(self, request, *args, **kwargs):
        card = get_object_or_404(Card, pk=self.kwargs['pk'])
        if request.user != card.user:
            return HttpResponseForbidden("Dis donc, c'est interdit ça de supprimer la carte des petits copains !")
        return super().dispatch(request, *args, **kwargs)

class DeckCreateView(CreateView):
    model = Deck
    fields = ['name', 'public']

    success_url = '/cards/'

    def form_valid(self, form):
        form.instance.user = self.request.user
        
        return super().form_valid(form)

def add_to_deck(request, card_id, deck_id):
    card = get_object_or_404(Card, pk=card_id)
    if request.user.is_authenticated:
        deck = get_object_or_404(Deck, pk=deck_id, user=request.user)
    if card in deck.cards.all():
        deck.cards.remove(card)
    else:
        deck.cards.add(card)

    return HttpResponseRedirect(reverse('cards:list'))

burgercriz/templates/apps.html
{% extends "base.html" %}
{% load static %}


{% block style %}
<style>
        
</style>
{% endblock %}

{% block apps_active %} active{% endblock %}

{% block content %}
<div class="container">
  <div class="row row-cols-1 row-cols-md-3 my-3 text-center justify-content-center">
    <div class="col">
      <div class="card mb-4 rounded-3 shadow-sm">
        <div class="card-header py-3">
          <h4 class="my-0 fw-normal">Application Windows</h4>
        </div>
        <div class="card-body">
          <img class="img-fluid" src="{% static "img/burger_windows.png" %}" alt="App Windows">
          <ul class="list-unstyled mt-3 mb-4">
            <li>Somptueuse interface</li>
            <li>Transitions vidéos</li>
            <li>Support cheesebuzzers USB</li>
            <li>Tableau de bord enseignant</li>
          </ul>
          <a class="w-100 btn btn-lg btn-primary" href="{% static "BurgerCriz.zip" %}" type="button"><i class="fas fa-download"></i> Télécharger l'application</a>  
        </div>
      </div>
    </div>
    <div class="col">
      <div class="card mb-4 rounded-3 shadow-sm">
        <div class="card-header py-3">
          <h4 class="my-0 fw-normal">Application web</h4>
        </div>
        <div class="card-body">
          <img class="img-fluid" src="{% static "img/burger_web.png" %}" alt="App Windows">
          <ul class="list-unstyled mt-3 mb-4">
            <li>Interface simple</li>
            <li>Sans installation</li>
            <li>Support cheesebuzzers USB</li>
            <li>&nbsp;</li>
          </ul>
          <a class="w-100 btn btn-lg btn-primary" href="#" type="button"><i class="fas fa-external-link-alt"></i> Ouvrir l'application web</a>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

burgercriz/templates/base.html
{% load static %}
<!doctype html>
<html lang="fr">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Burger Criz : Un jeu qu'il est bien !">
    <meta name="author" content="Baptiste Gaultier">

    <title>Burger Criz</title>
    
    <!-- Bootstrap core CSS -->
    <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">

    <!-- Custom fonts for this template-->
    <link href="{% static "vendor/fontawesome-free/css/all.min.css" %}" rel="stylesheet" type="text/css">
    <link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Comic+Neue:wght@700&display=swap" rel="stylesheet">
    
    <!-- Custom styles for this template-->
    <style> @import url('https://fonts.googleapis.com/css2?family=Comic+Neue:wght@700&display=swap'); </style>
    <style>
        /* Padding below the footer and lighter body text */
        body {
            padding-top: 5rem;
            padding-bottom: 3rem;
        }
    </style>
    {% block style %}{% endblock %}

    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="{% static "img/favicon144.png" %}">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="{% static "img/favicon114.png" %}">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="{% static "img/favicon72.png" %}">
    <link rel="apple-touch-icon-precomposed" href="{% static "img/favicon57.png" %}">
    <link rel="shortcut icon" href="{% static "img/favicon32.png" %}">
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-black">
            <a class="navbar-brand mx-4" href="{% url 'home' %}"><img src="{% static "img/burger_criz_logo.svg" %}" alt="Logo Burger Criz" height="24"></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item">
                        <a class="nav-link{% block home_active %}{% endblock %}" href="/">Accueil</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link{% block cards_active %}{% endblock %}" href="{% url 'cards:list' %}">Cartes</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {% block apps_active %}{% endblock %}" href="{% url 'apps' %}">Animer une session</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link{% block help_active %}{% endblock %}" href="{% url 'help' %}">Aide</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {% block user_active %}{% endblock %}" href="{% if user.is_authenticated %}{% url 'profile' %}{% else %}{% url 'login' %}{% endif %}">
                            {% if user.is_authenticated %}
                            <i class="fas fa-user-cog"></i>
                            {% else %}
                            <i class="fas fa-sign-in-alt"></i>
                            {% endif %}
                        </a>
                    </li>
                    {% if user.is_authenticated and user.is_staff %}
                    <li class="nav-item">
                        <a class="nav-link" href="/admin">Admin <i class="fas fa-lock"></i></a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </nav>
    </header>
    <main role="main">
        {% block content %}{% endblock %}

        <!-- FOOTER -->
        <footer class="container my-5">
            <p>&copy; 2022 <a href="https://www.imt.fr/" style="color:#00B8DE"><img src="{% static "img/imt.svg" %}" alt="Logo Institut Mines Télécom" height=16 style="margin-top:-2px"></a></p>
        </footer>
    </main>

    <!-- Bootstrap core JavaScript-->
    <script src="{% static "vendor/bootstrap/js/bootstrap.bundle.min.js" %}" type="text/javascript"></script>
    {% block scripts %}
	{% endblock %}
</body>

</html>

burgercriz/templates/help.html
{% extends "base.html" %}
{% load static %}

{% block help_active %} active{% endblock %}

{% block content %}
<div class="col-lg-8 mx-auto p-4 py-md-5">
    <p class="fs-5">Si vous cherchez comment réaliser une action en utilisant ce site. Vous êtes au bon endroit !</p>
    <main>
        <h3>Comment créer une carte ?</h3>
        <ul>
            <li>Pour créer une carte, vous devez disposer d'un compte et être authentifié. Pour cela, cliquer sur l'icône <i class="fas fa-sign-in-alt"></i> en haut à droite.</li>
            <li>Rendez-vous sur la page <a href="{% url 'cards:list' %}">Cartes</a>.</li>
            <li>Cliquez sur le bouton <a href="#" class="btn btn-primary ms-auto"><i class="far fa-plus-square"> </i> Créer une carte</a>.</li>
            <li>Remplissez le formulaire qui s'affiche en utilisant le langage Markdown.</li>
        </ul>

        <hr class="mb-5">

        <h3>Comment créer un paquet de cartes ?</h3>
        <ul>
            <li>Pour créer un paquet de cartes (en vue de l'imprimer ou de l'utiliser depuis votre téléphone), vous devez disposer d'un compte et être authentifié. Pour cela, cliquer sur l'icône <i class="fas fa-sign-in-alt"></i> en haut à droite.</li>
            <li>Créer un paquet de carte en cliquant sur le bouton <button type="button" class="btn btn-dark btn-sm"><i class="fas fa-layer-group"></i></button> d'une carte et sélectionner « <i class="far fa-plus-square"></i> Nouveau paquet de carte ».</li>
            <li>Remplissez le formulaire.</li>
        </ul>

        <hr class="mb-5">
    </main>
</div>
{% endblock %}

burgercriz/templates/home.html
{% extends "base.html" %}
{% load static %}
{% block style %}
<link href="{% static "css/carousel.css" %}" rel="stylesheet">
{% endblock %}

{% block home_active %} active{% endblock %}

{% block content %}
<div id="myCarousel" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-indicators">
        <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Diapo 1"></button>
        <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="1" aria-label="Diapo 2"></button>
    </div>
    <div class="carousel-inner">
        <div class="carousel-item active">
            <video autoplay muted loop class="video-bg" object-fit="cover"  style="filter: brightness(50%) blur(5px); height: 512px; width: 100%;">
                <source src="{% static "img/teaser.mp4" %}" type="video/mp4">
            </video>
            <div class="container">
                <div class="carousel-caption text-start">
                    <h1>Burger Criz est en ligne !</h1>
                    <p>Le « serious game » où la culture a rendez-vous avec la classe.</p>
                    <p><a class="btn btn-lg btn-primary" href="https://www.youtube.com/watch?v=Y1_D41V9jOE" target="_blank"><i class="fab fa-youtube"></i> Voir le teaser</a></p>
                </div>
            </div>
        </div>
        <div class="carousel-item">
            <img src="{% static "img/flo_regles.png" %}"  alt="Aperçu vidéo règles" style="filter: brightness(50%) blur(5px); height: 512px; width: 100%; object-fit: cover;">
            <div class="container">
                <div class="carousel-caption">  
                    <h1>Ludifiez vos cours !</h1>
                    <p>Burger Criz est un jeu de société pédagogique qui permet d'aborder des notions de théoriques pour la gestion de crise dans le domaine des risques naturels et industriels (parfois, les questions seront marrantes !)</p>
                    <p><a class="btn btn-lg btn-primary" href="https://www.youtube.com/watch?v=05eGJz_-mB4" target="_blank"><i class="fab fa-youtube"></i> Découvrez les règles</a></p>
                </div>
            </div>
        </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#myCarousel" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Précédent</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#myCarousel" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Suivant</span>
    </button>
</div>


<!-- Marketing messaging and featurettes
  ================================================== -->
<!-- Wrap the rest of the page in another container to center all the content. -->

<div class="container marketing">

    <!-- Three columns of text below the carousel -->
    <div class="row">
        <div class="col-lg-4">
            <img src="{% static "img/cartes.png" %}"  alt="Cartes Burger Criz" style="width: 140px; height: 140px; border-radius: 50%;">
            <h2 class="fw-normal">Banque de cartes</h2>
            <p>Burger Criz se joue avec des cartes « questions » portant sur de nombreuses thématiques. Mieux : vous pouvez même créer les vôtres et les partager sur ce site !</p>
            <p><a class="btn btn-secondary" href="{% url 'cards:list' %}"><i class="fas fa-layer-group"></i> Les cartes</a></p>
        </div>
        <!-- /.col-lg-4 -->
        <div class="col-lg-4">
            <img src="{% static "img/burger_de_chantier.png" %}"  alt="Burger de chantier" style="width: 140px; height: 140px; border-radius: 50%;">
            <h2 class="fw-normal">Fabriquez le vôtre</h2>
            <p>Un tutoriel pour fabriquer vos buzzers et vos cartes sera bientôt disponible en ligne. Pour quelques dizaines d'euros, ce sera comme si vous aviez le plateau TV dans votre classe.</p>
            <p><a class="btn btn-secondary disabled" href="">À venir</a></p>
        </div>
        <!-- /.col-lg-4 -->
        <div class="col-lg-4">
            <img src="{% static "img/frites-open-source.svg" %}"  alt="Open Source" style="width: 140px; height: 140px; border-radius: 50%;">
            <h2 class="fw-normal">Logiciel libre</h2>
            <p>Le code de cette application web est ouvert et libre. Il est mise à disposition gratuitement sous licence <a href="https://github.com/imt-atlantique/burgercriz" target="_blank">AGPLv3</a>.</p>
            <p><a class="btn btn-secondary" href="https://github.com/imt-atlantique/burgercriz"><i class="fas fa-code-branch"></i> Le code</a></p>
        </div>
        <!-- /.col-lg-4 -->
    </div>
    <!-- /.row -->


    <!-- START THE FEATURETTES -->

    <hr class="featurette-divider">

    <!-- /END THE FEATURETTES -->

</div>
<!-- /.container -->
{% endblock %}

cards/templates/cards/card_list.html
{% extends "base.html" %}
{% load static %}
{% load humanize %}

{% block cards_active %} active{% endblock %}

{% block style %}
<style>
  .card-body ol {
    padding-left: 1rem;
  }

  .card-body ul {
    padding-left: 8px;
  }

  .card-body ul>li {
    list-style-type: '- ';
  }

  .card-body ol>li {
    list-style-type: upper-alpha!important
  }

  .card-body {
    font-family: 'Comic Sans MS', 'Comic Neue';
    font-size: 10px;
    color: black;
  }

  .card-text {
    border-radius: 8px
  }
  
  .card-body p {
    margin-bottom: 0
  }

  .nuggets.card-background {
    background-color: #c5c61d
  }

  .menu-bleu.card-background {
    background-color: #36c4f1
  }

  .menu-rouge.card-background {
    background-color: #f52513
  }

  .addition.card-background {
    background-color: #f99b7f
  }

  .seloupoivre.card-background {
    background-color: #88898b
  }

  .burgerdelamort.card-background {
    background-color: #84be23
  }

  .nuggets.card-text {
    background-color: #f5f6e1;
  }

  .menu-bleu.card-text {
    background-color: #f5f6e1
  }

  .seloupoivre.card-text {
    background-color: #f3f4f4
  }

  .menu-rouge.card-text {
    background-color: #f5f7fc
  }

  .addition.card-text {
    background-color: #f5e9e9
  }

  .burgerdelamort.card-text {
    background-color: #e9efdd
  }
</style>
{% endblock %}

{% block content %}
<ul class="nav nav-pills m-4">
  <li class="nav-item">
    <a class="nav-link disabled" href="">Filtres : </a>
  </li>
  <li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle{% if request.GET.tag %} active{% endif %}" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">{% if request.GET.tag %}{{ request.GET.tag }}{% else %}Tags{% endif %}</a>
    <div class="dropdown-menu" style="">
      {% for tag in tags %}
      <a class="dropdown-item" href="{% url 'cards:list' %}?tag={{ tag }}">{{ tag.tag|slice:":1"|upper }}{{ tag.tag|slice:"1:" }}</a>
      {% endfor %}
    </div>
  </li>
  <li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle{% if request.GET.deck %} active{% endif %}" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">{% if request.GET.deck %}{{ request.GET.deck }}{% else %}Paquets de cartes publics{% endif %}</a>
    <div class="dropdown-menu" style="">
      {% for deck in public_decks %}
      <a class="dropdown-item" href="{% url 'cards:list' %}?deck={{ deck }}">{{ deck.name|slice:":1"|upper }}{{ deck.name|slice:"1:" }}</a>
      {% endfor %}
    </div>
  </li>
  <li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle{% if request.GET.type %} active{% endif %}" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Type</a>
    <div class="dropdown-menu" style="">
      {% for type in card_types %}
      <a class="dropdown-item" href="{% url 'cards:list' %}?type={{ type.0 }}">{{ type.1 }}</a>
      {% endfor %}
    </div>
  </li>
  {% if request.GET.tag or request.GET.deck or request.GET.type %}
  <li class="nav-item">
    <a class="btn btn-outline-primary mx-2" href="{% url 'cards:list' %}"><i class="far fa-times-circle"></i> Effacer les filtres</a>
  </li>
  {% endif %}

{% if user.is_authenticated %}<a href="{% url 'cards:create' %}" class="btn btn-primary ms-auto mx-5"><i class="far fa-plus-square"> </i> Créer une carte</a>{% endif %}
</ul>
<div class="container">
  <div class="row">
    {% for card in object_list %}
      <div class="col-md-4">
          <div class="card mb-4 shadow-sm">
            <div class="card-header">{{ card }}&nbsp;{% for tag in card.tags.all %}
              <span class="badge bg-dark">#{{ tag }}</span>
              {% endfor %}</div>
              <div class="card-body bg-black p-0" style="max-height: 156px;">
                <div class="d-flex align-items-center">
                  <div class="flex-shrink-1 p-1"><img src="{% if card.type == 0 %}toss{% elif card.type == 1 %}{% static "img/nuggets.svg" %}{% elif card.type == 2 %}{% static "img/seloupoivre.svg" %}{% elif card.type == 3 or card.type == 4 %}{% static "img/menus.svg" %}{% elif card.type == 5 %}{% static "img/addition.svg" %}{% elif card.type == 6 %}{% static "img/burgerdelamort.svg" %}{% endif %}" alt="Logo Burger Criz" height="128"></div>
                  <div class="{% if card.type == 0 %}toss{% elif card.type == 1 %}nuggets{% elif card.type == 2 %}seloupoivre{% elif card.type == 3 %}menu-bleu{% elif card.type == 4 %}menu-rouge{% elif card.type == 5 %}addition{% elif card.type == 6 %}burgerdelamort{% endif %} card-background p-2 w-100">
                    <div class="{% if card.type == 0 %}toss{% elif card.type == 1 %}nuggets{% elif card.type == 2 %}seloupoivre{% elif card.type == 3 %}menu-bleu{% elif card.type == 4 %}menu-rouge{% elif card.type == 5 %}addition{% elif card.type == 6 %}burgerdelamort{% endif %} card-text p-1" style="height: 140px;">{{ card.text_rendered|safe }}</div>
                  </div>
                </div>
              </div>
              <div class="card-footer text-muted">
                <div class="d-flex justify-content-between align-items-center">
                  {% if user.is_authenticated %}
                  <div class="btn-group">
                    {% if user == card.user %}<a href="{% url 'cards:update' card.id %}" class="btn btn-dark btn-sm"><i class="far fa-edit"></i></a>{% endif %}
                      <div class="btn-group" role="group">
                        <button id="btnGroupDrop{{ card.id }}" type="button" class="btn btn-dark btn-sm dropdown-toggle" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fas fa-layer-group"></i></button>
                        <div class="dropdown-menu" aria-labelledby="btnGroupDrop1">
                          {% for deck in decks %}
                          <a class="dropdown-item" href="{% url 'cards:add_to_deck' card.id deck.id %}" onclick="document.getElementById('btnGroupDrop{{ card.id }}').classList.remove('btn-dark'); document.getElementById('btnGroupDrop{{ card.id }}').classList.add('btn-success');">{% if card in deck.cards.all %}<i class="far fa-check-circle"></i> {% else %}<i class="far fa-circle"></i> {% endif %}{{ deck }}</a>
                          {% endfor %}
                          <a class="dropdown-item" href="{% url 'cards:new_deck' card.id %}"><i class="far fa-plus-square"></i> Nouveau paquet de carte</a>
                        </div>
                      </div>
                      {% if user == card.user %}<a href="{% url 'cards:delete' card.id %}" class="btn btn-danger btn-sm"><i class="far fa-trash-alt"></i></a>{% endif %}
                  </div>
                  {% endif %}
                  <small class="text-muted">{{ card.modified_date|naturaltime }}</small>
                </div>
              </div>
          </div>
      </div>
    {% endfor %}
    <div class="btn-toolbar my-2" role="toolbar" aria-label="Pages">
      <div class="btn-group me-2" role="group">
        {% if page_obj.has_previous %}
          <a class="btn btn-secondary" href="?page=1"><i class="fas fa-fast-backward"></i></a>
          <a class="btn btn-secondary" href="?page={{ page_obj.previous_page_number }}"><i class="fas fa-step-backward"></i></a>
        {% endif %}
        <a class="btn btn-secondary">{{ page_obj.number }}</a>
        {% if page_obj.has_next %}
            <a class="btn btn-secondary" href="?page={{ page_obj.next_page_number }}"><i class="fas fa-step-forward"></i></a>
            <a class="btn btn-secondary" href="?page={{ page_obj.paginator.num_pages }}"><i class="fas fa-fast-forward"></i></a>
        {% endif %}
      </div>
    </div>
</div>
{% endblock %}